### ISSUE TITLE
pre-receive hook ruby error

### ISSUE THREAD

**Issue by srianirudh84** [drwahl/puppet-git-hooks#35]
The pre-receive hook does not seem to work well with CentOS 7 and puppet 3.8.1

I get this error while committing, not sure what this error mean

git push
Counting objects: 11, done.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (9/9), 718 bytes, done.
Total 9 (delta 3), reused 0 (delta 0)
remote: Checking puppet manifest syntax for site.pp...
remote: /usr/share/rubygems/rubygems/path_support.rb:68:in `path=': undefined method `+' for nil:NilClass (NoMethodError)
remote: from /usr/share/rubygems/rubygems/path_support.rb:30:in `initialize'
remote: from /usr/share/rubygems/rubygems.rb:357:in `new'
remote: from /usr/share/rubygems/rubygems.rb:357:in `paths'
remote: from /usr/share/rubygems/rubygems.rb:379:in `path'
remote: from /usr/share/rubygems/rubygems/specification.rb:794:in `dirs'
remote: from /usr/share/rubygems/rubygems/specification.rb:658:in `each_normal'
remote: from /usr/share/rubygems/rubygems/specification.rb:669:in `_all'
remote: from /usr/share/rubygems/rubygems/specification.rb:822:in `each'
remote: from /usr/share/rubygems/rubygems/specification.rb:864:in `find'
remote: from /usr/share/rubygems/rubygems/specification.rb:864:in `find_inactive_by_path'
remote: from /usr/share/rubygems/rubygems.rb:175:in `try_activate'
remote: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
remote: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
remote: from <internal:abrt_prelude>:2:in `<compiled>'
remote: Error: puppet syntax error in site.pp (see above)
remote: Error: 1 syntax error(s) found in puppet manifests. Commit will be aborted.
remote: puppet-lint not installed. Skipping puppet-lint tests...
remote: Error: 1 subhooks failed. Declining push.

**Comment by srianirudh84** [comment]
I am using gitlab on Centos 7

**Comment by mrjoshuap** [comment]
Is Puppet version 3.8.1 installed on both CentOS 6 and 7?  What version(s) of Ruby are you running?

**Comment by srianirudh84** [comment]
Hey My puppet version is 3.8.1 and my ruby version is 1.8.7. It got installed when i installed the puppet agent. It comes with facter and  ruby as dependencies.
